<?php
/**
 * Drop-in replacement for PHP core function mime_content_type
 *
 * $Id: mime-array.php,v 1.6 2006/02/03 21:46:20 jswalter Exp $
 */
if ( !defined('IN_XRMS') )
{
  die('Hacking attempt');
  exit;
}

//if (!function_exists('mime_content_type')){
/**
 * find and return the mime type
 *
 * This function serves as a drop-in replacement for
 * the core PHP function mime_content_type.
 * Many versions of PHP do not have the mime
 * functions built in, so we need to replace it
 * with a suitable replacement.
 *
 * @param string $file_system_name
 * @return string of mime type
 */
function mime_content_type_ ( $file_system_name )
{
    global $mime_array;

    $tmp = substr(strrchr(strtolower($file_system_name),'.'),1);

    //
    // This file declares an array who's key is the
    // file extension, and the data is the mime type
    //
    // To update this array:
    //
    // 1. get latest copy of mime.types. See the mime.types included in this kit
    //    for its location.
    // 2. make
    // 3. ./gmime | sort | uniq > zz
    // 4. then cut and paste zz into this file
    // 5. rm zz
    //
    // If you are running Micro$oft Window$, you'll
    // have to install cygwin first before the make
    // will work.
    //
    // To get the mime type of any file extension,
    // just do:
    //
    //    $mime-type = $mime_array['file-extension'];
    //
    $mime_array = array ( // ext => type

        '1' => 'application/wordperfect5.1',
        '1' => 'audio/g.722.1',
        '32kadpcm' => 'audio/32kadpcm',
        '32kadpcm' => 'audio/vnd.rhetorex.32kadpcm',
        '3dml' => 'model/vnd.flatland.3dml',
        '3dml' => 'text/vnd.flatland.3dml',
        '3dml' => 'text/vnd.in3d.3dml',
        'abc' => 'text/vnd.abc',
        'activemessage' => 'application/activemessage',
        'acucobol' => 'application/vnd.acucobol',
        'adsi' => 'application/vnd.motorola.flexsuite.adsi',
        'afplinedata' => 'application/vnd.ibm.afplinedata',
        'ai' => 'application/postscript',
        'aif' => 'audio/x-aiff',
        'aifc' => 'audio/x-aiff',
        'aiff' => 'audio/x-aiff',
        'alert' => 'application/vnd.uplanet.alert',
        'alert-wbxml' => 'application/vnd.uplanet.alert-wbxml',
        'alternative' => 'multipart/alternative',
        'andrew-inset' => 'application/andrew-inset',
        'anp1' => 'audio/vnd.cns.anp1',
        'anser-web-certificate-issue-initiation' => 'application/vnd.anser-web-certificate-issue-initiation',
        'anser-web-funds-transfer-initiation' => 'application/vnd.anser-web-funds-transfer-initiation',
        'appledouble' => 'multipart/appledouble',
        'applefile' => 'application/applefile',
        'asc' => 'text/plain',
        'aso' => 'application/vnd.accpac.simply.aso',
        'atomicmail' => 'application/atomicmail',
        'au' => 'audio/basic',
        'audiograph' => 'application/vnd.audiograph',
        'avi' => 'video/x-msvideo',
        'basic' => 'audio/basic',
        'batch-SMTP' => 'application/batch-SMTP',
        'bcpio' => 'application/x-bcpio',
        'bearer-choice' => 'application/vnd.uplanet.bearer-choice',
        'bearer-choice-wbxml' => 'application/vnd.uplanet.bearer-choice-wbxml',
        'beep+xml' => 'application/beep+xml',
        'bin' => 'application/octet-stream',
        'binder' => 'application/vnd.fujixerox.docuworks.binder',
        'bmi' => 'application/vnd.bmi',
        'bmp' => 'image/bmp',
        'box' => 'application/vnd.previewsystems.box',
        'btif' => 'image/prs.btif',
        'businessobjects' => 'application/vnd.businessobjects',
        'byteranges' => 'multipart/byteranges',
        'cacheop' => 'application/vnd.uplanet.cacheop',
        'cacheop-wbxml' => 'application/vnd.uplanet.cacheop-wbxml',
        'calendar' => 'text/calendar',
        'cals-1840' => 'application/cals-1840',
        'canon-cpdl' => 'application/vnd.canon-cpdl',
        'canon-lips' => 'application/vnd.canon-lips',
        'cdf' => 'application/x-netcdf',
        'cdkey' => 'application/vnd.mediastation.cdkey',
        'cgm' => 'image/cgm',
        'channel' => 'application/vnd.uplanet.channel',
        'channel-wbxml' => 'application/vnd.uplanet.channel-wbxml',
        'chart' => 'application/vnd.ecowin.chart',
        'class' => 'application/octet-stream',
        'claymore' => 'application/vnd.claymore',
        'cmd' => 'application/index.cmd',
        'cmsg' => 'application/vnd.contact.cmsg',
        'commerce-battelle' => 'application/vnd.commerce-battelle',
        'commonground' => 'application/commonground',
        'commonspace' => 'application/vnd.commonspace',
        'comsocaller' => 'application/vnd.comsocaller',
        'cosmocaller' => 'application/vnd.cosmocaller',
        'cpio' => 'application/x-cpio',
        'cpt' => 'application/mac-compactpro',
        'csh' => 'application/x-csh',
        'css' => 'text/css',
        'ctc-posml' => 'application/vnd.ctc-posml',
        'cups-postscript' => 'application/vnd.cups-postscript',
        'cups-raster' => 'application/vnd.cups-raster',
        'cups-raw' => 'application/vnd.cups-raw',
        'curl' => 'text/vnd.curl',
        'cvsd' => 'audio/vnd.vmx.cvsd',
        'cww' => 'application/prs.cww',
        'cybank' => 'application/vnd.cybank',
        'cybercash' => 'application/cybercash',
        'daf' => 'application/vnd.mobius.daf',
        'data' => 'application/vnd.eudora.data',
        'dca-rft' => 'application/dca-rft',
        'dcr' => 'application/x-director',
        'ddd' => 'application/vnd.fujixerox.ddd',
        'dec-dx' => 'application/dec-dx',
        'delivery-status' => 'message/delivery-status',
        'digest' => 'multipart/digest',
        'digibox' => 'application/vnd.intertrust.digibox',
        'digital-winds' => 'audio/vnd.digital-winds',
        'dir' => 'application/x-director',
        'directory' => 'text/directory',
        'dis' => 'application/vnd.mobius.dis',
        'disposition-notification' => 'message/disposition-notification',
        'djv' => 'image/vnd.djvu',
        'djvu' => 'image/vnd.djvu',
        'dll' => 'application/octet-stream',
        'DMClientScript' => 'text/vnd.DMClientScript',
        'dms' => 'application/octet-stream',
        'dna' => 'application/vnd.dna',
        'doc' => 'application/msword',
        'docuworks' => 'application/vnd.fujixerox.docuworks',
        'dpgraph' => 'application/vnd.dpgraph',
        'dvcs' => 'application/dvcs',
        'dvi' => 'application/x-dvi',
        'dwf' => 'model/vnd.dwf',
        'dwg' => 'image/vnd.dwg',
        'dxf' => 'image/vnd.dxf',
        'dxr' => 'application/vnd.dxr',
        'dxr' => 'application/x-director',
        'ecdis-update' => 'application/vnd.ecdis-update',
        'ecelp4800' => 'audio/vnd.nuera.ecelp4800',
        'ecelp7470' => 'audio/vnd.nuera.ecelp7470',
        'ecelp9600' => 'audio/vnd.nuera.ecelp9600',
        'EDI-Consent' => 'application/EDI-Consent',
        'EDIFACT' => 'application/EDIFACT',
        'EDI-X12' => 'application/EDI-X12',
        'EDM' => 'application/vnd.novadigm.EDM',
        'edmics-mmr' => 'image/vnd.fujixerox.edmics-mmr',
        'edmics-rlc' => 'image/vnd.fujixerox.edmics-rlc',
        'EDX' => 'application/vnd.novadigm.EDX',
        'encrypted' => 'multipart/encrypted',
        'enliven' => 'application/vnd.enliven',
        'enriched' => 'text/enriched',
        'eps' => 'application/postscript',
        'esf' => 'application/vnd.epson.esf',
        'eshop' => 'application/eshop',
        'etx' => 'text/x-setext',
        'exe' => 'application/octet-stream',
        'EXT' => 'application/vnd.novadigm.EXT',
        'external-body' => 'message/external-body',
        'ez' => 'application/andrew-inset',
        'fastbidsheet' => 'image/vnd.fastbidsheet',
        'fdf' => 'application/vnd.fdf',
        'ffsns' => 'application/vnd.ffsns',
        'filerequest' => 'application/vnd.ecowin.filerequest',
        'fileupdate' => 'application/vnd.ecowin.fileupdate',
        'fis' => 'application/vnd.motorola.flexsuite.fis',
        'flexstor' => 'text/vnd.fmi.flexstor',
        'flexsuite' => 'application/vnd.motorola.flexsuite',
        'FloGraphIt' => 'application/vnd.FloGraphIt',
        'fly' => 'text/vnd.fly',
        'font-tdpfr' => 'application/font-tdpfr',
        'format' => 'application/vnd.pg.format',
        'formdata' => 'application/vnd.shana.informed.formdata',
        'form-data' => 'multipart/form-data',
        'formnet' => 'application/vnd.intercon.formnet',
        'formtemplate' => 'application/vnd.shana.informed.formtemplate',
        'fpx' => 'image/vnd.fpx',
        'framemaker' => 'application/vnd.framemaker',
        'fst' => 'image/vnd.fst',
        'fut-misnet' => 'application/vnd.fut-misnet',
        'fvt' => 'video/vnd.fvt',
        'g3fax' => 'image/g3fax',
        'gdl' => 'model/vnd.gdl',
        'gif' => 'image/gif',
        'gotap' => 'application/vnd.motorola.flexsuite.gotap',
        'grafeq' => 'application/vnd.grafeq',
        'groove-account' => 'application/vnd.groove-account',
        'groove-identity-message' => 'application/vnd.groove-identity-message',
        'groove-injector' => 'application/vnd.groove-injector',
        'groove-tool-message' => 'application/vnd.groove-tool-message',
        'groove-tool-template' => 'application/vnd.groove-tool-template',
        'groove-vcard' => 'application/vnd.groove-vcard',
        'gs-gdl' => 'model/vnd.gs-gdl',
        'gtar' => 'application/x-gtar',
        'gtw' => 'model/vnd.gtw',
        'hdf' => 'application/x-hdf',
        'header-set' => 'multipart/header-set',
        'hp-HPGL' => 'application/vnd.hp-HPGL',
        'hp-hpid' => 'application/vnd.hp-hpid',
        'hp-hps' => 'application/vnd.hp-hps',
        'hp-PCL' => 'application/vnd.hp-PCL',
        'hp-PCLXL' => 'application/vnd.hp-PCLXL',
        'hqx' => 'application/mac-binhex40',
        'html' => 'text/html',
        'htm' => 'text/html',
        'http' => 'application/http',
        'httphone' => 'application/vnd.httphone',
        'http' => 'message/http',
        'hyperstudio' => 'application/hyperstudio',
        'hzn-3d-crossword' => 'application/vnd.hzn-3d-crossword',
        'ice' => 'x-conference/x-cooltalk',
        'ief' => 'image/ief',
        'iges' => 'application/iges',
        'iges' => 'model/iges',
        'igs' => 'model/iges',
        'imp' => 'application/vnd.accpac.simply.imp',
        'imp' => 'application/vnd.aether.imp',
        'index' => 'application/index',
        'inf1' => 'audio/vnd.cns.inf1',
        'inf2' => 'image/vnd.cns.inf2',
        'informix-visionary' => 'application/vnd.informix-visionary',
        'interchange' => 'application/vnd.shana.informed.interchange',
        'interleaved-multimedia' => 'video/vnd.nokia.interleaved-multimedia',
        'iotp' => 'application/iotp',
        'ipp' => 'application/ipp',
        'isup' => 'application/isup',
        'is-xpr' => 'application/vnd.is-xpr',
        'japannet-directory-service' => 'application/vnd.japannet-directory-service',
        'japannet-jpnstore-wakeup' => 'application/vnd.japannet-jpnstore-wakeup',
        'japannet-payment-wakeup' => 'application/vnd.japannet-payment-wakeup',
        'japannet-registration' => 'application/vnd.japannet-registration',
        'japannet-registration-wakeup' => 'application/vnd.japannet-registration-wakeup',
        'japannet-setstore-wakeup' => 'application/vnd.japannet-setstore-wakeup',
        'japannet-verification' => 'application/vnd.japannet-verification',
        'japannet-verification-wakeup' => 'application/vnd.japannet-verification-wakeup',
        'jpeg' => 'image/jpeg',
        'jpe' => 'image/jpeg',
        'jpg' => 'image/jpeg',
        'js' => 'application/x-javascript',
        'kar' => 'audio/midi',
        'kmr' => 'application/vnd.motorola.flexsuite.kmr',
        'koan' => 'application/vnd.koan',
        'l16' => 'audio/l16',
        'latex' => 'application/x-latex',
        'latex-z' => 'text/vnd.latex-z',
        'lesson-player' => 'application/vnd.hhe.lesson-player',
        'lha' => 'application/octet-stream',
        'list' => 'application/vnd.uplanet.list',
        'listcmd' => 'application/vnd.uplanet.listcmd',
        'listcmd-wbxml' => 'application/vnd.uplanet.listcmd-wbxml',
        'list-wbxml' => 'application/vnd.uplanet.list-wbxml',
        'lotus-1-2-3' => 'application/vnd.lotus-1-2-3',
        'lotus-approach' => 'application/vnd.lotus-approach',
        'lotus-freelance' => 'application/vnd.lotus-freelance',
        'lotus-notes' => 'application/vnd.lotus-notes',
        'lotus-organizer' => 'application/vnd.lotus-organizer',
        'lotus-screencam' => 'application/vnd.lotus-screencam',
        'lotus-wordpro' => 'application/vnd.lotus-wordpro',
        'lzh' => 'application/octet-stream',
        'm3u' => 'audio/x-mpegurl',
        'mac-binhex40' => 'application/mac-binhex40',
        'mac-compactpro' => 'application/mac-compactpro',
        'macwriteii' => 'application/macwriteii',
        'man' => 'application/x-troff-man',
        'marc' => 'application/marc',
        'mathematica' => 'application/mathematica',
        'mathematica-old' => 'application/mathematica-old',
        'mcd' => 'application/vnd.mcd',
        'me' => 'application/x-troff-me',
        'meridian-slingshot' => 'application/vnd.meridian-slingshot',
        'mesh' => 'model/mesh',
        'mid' => 'audio/midi',
        'midi' => 'audio/midi',
        'mif' => 'application/vnd.mif',
        'MiniPay' => 'application/vnd.ibm.MiniPay',
        'minisoft-hp3000-save' => 'application/vnd.minisoft-hp3000-save',
        'mixed' => 'multipart/mixed',
        'mix' => 'image/vnd.mix',
        'modcap' => 'application/vnd.ibm.modcap',
        'movie' => 'video/x-sgi-movie',
        'mov' => 'video/quicktime',
        'mp2' => 'audio/mpeg',
        'mp3' => 'audio/mpeg',
        'mp4a-latm' => 'audio/mp4a-latm',
        'mp4v-es' => 'video/mp4v-es',
        'mpa-robust' => 'audio/mpa-robust',
        'mpeg' => 'audio/mpeg',
        'mpegurl' => 'video/vnd.mpegurl',
        'mpeg' => 'video/mpeg',
        'mpe' => 'video/mpeg',
        'mpga' => 'audio/mpeg',
        'mpg' => 'video/mpeg',
        'ms' => 'application/x-troff-ms',
        'ms-artgalry' => 'application/vnd.ms-artgalry',
        'ms-asf' => 'application/vnd.ms-asf',
        'mseq' => 'application/vnd.mseq',
        'ms-excel' => 'application/vnd.ms-excel',
        'msf' => 'application/vnd.epson.msf',
        'msh' => 'model/mesh',
        'msign' => 'application/vnd.msign',
        'msl' => 'application/vnd.mobius.msl',
        'ms-lrm' => 'application/vnd.ms-lrm',
        'ms-mediapackage' => 'text/vnd.ms-mediapackage',
        'ms-powerpoint' => 'application/vnd.ms-powerpoint',
        'ms-project' => 'application/vnd.ms-project',
        'ms-tnef' => 'application/vnd.ms-tnef',
        'msword' => 'application/msword',
        'ms-works' => 'application/vnd.ms-works',
        'mts' => 'model/vnd.mts',
        'mts' => 'video/vnd.mts',
        'musician' => 'application/vnd.musician',
        'music-niff' => 'application/vnd.music-niff',
        'mxs' => 'application/vnd.triscape.mxs',
        'mxu' => 'video/vnd.mpegurl',
        'naplps' => 'image/naplps',
        'nc' => 'application/x-netcdf',
        'netdeploy' => 'application/vnd.osa.netdeploy',
        'netfpx' => 'application/vnd.netfpx',
        'net-fpx' => 'image/vnd.net-fpx',
        'news-message-id' => 'application/news-message-id',
        'news' => 'message/news',
        'NewsML' => 'text/vnd.IPTC.NewsML',
        'news-transmission' => 'application/news-transmission',
        'NITF' => 'text/vnd.IPTC.NITF',
        'nncp' => 'application/vnd.intertrust.nncp',
        'noblenet-directory' => 'application/vnd.noblenet-directory',
        'noblenet-sealer' => 'application/vnd.noblenet-sealer',
        'noblenet-web' => 'application/vnd.noblenet-web',
        'nprend' => 'application/prs.nprend',
        'nse' => 'audio/vnd.cisco.nse',
        'oasys2' => 'application/vnd.fujitsu.oasys2',
        'oasys3' => 'application/vnd.fujitsu.oasys3',
        'oasys' => 'application/vnd.fujitsu.oasys',
        'oasysgp' => 'application/vnd.fujitsu.oasysgp',
        'oasysprs' => 'application/vnd.fujitsu.oasysprs',
        'obj' => 'application/index.obj',
        'ocsp-request' => 'application/ocsp-request',
        'ocsp-response' => 'application/ocsp-response',
        'octet-stream' => 'application/octet-stream',
        'oda' => 'application/oda',
        'osasli' => 'application/vnd.pg.osasli',
        'package' => 'application/vnd.shana.informed.package',
        'package+xml' => 'application/vnd.irepository.package+xml',
        'palm' => 'application/vnd.palm',
        'parallel' => 'multipart/parallel',
        'parityfec' => 'application/parityfec',
        'parityfec' => 'audio/parityfec',
        'parityfec' => 'text/parityfec',
        'parityfec' => 'video/parityfec',
        'partial' => 'message/partial',
        'pbm' => 'image/x-portable-bitmap',
        'pdb' => 'chemical/x-pdb',
        'pdf' => 'application/pdf',
        'pgm' => 'image/x-portable-graymap',
        'pgn' => 'application/x-chess-pgn',
        'pgp-encrypted' => 'application/pgp-encrypted',
        'pgp-keys' => 'application/pgp-keys',
        'pgp-signature' => 'application/pgp-signature',
        'pkcs10' => 'application/pkcs10',
        'pkcs7-mime' => 'application/pkcs7-mime',
        'pkcs7-signature' => 'application/pkcs7-signature',
        'pkix-cert' => 'application/pkix-cert',
        'pkixcmp' => 'application/pkixcmp',
        'pkix-crl' => 'application/pkix-crl',
        'plain' => 'text/plain',
        'plc' => 'application/vnd.mobius.plc',
        'plj' => 'audio/vnd.everad.plj',
        'png' => 'image/png',
        'pnm' => 'image/x-portable-anymap',
        'pointer' => 'video/pointer',
        'Post-it-Notes' => 'application/vnd.3M.Post-it-Notes',
        'postscript' => 'application/postscript',
        'powerbuilder6' => 'application/vnd.powerbuilder6',
        'powerbuilder6-s' => 'application/vnd.powerbuilder6-s',
        'powerbuilder75' => 'application/vnd.powerbuilder75',
        'powerbuilder75-s' => 'application/vnd.powerbuilder75-s',
        'powerbuilder7' => 'application/vnd.powerbuilder7',
        'powerbuilder7-s' => 'application/vnd.powerbuilder7-s',
        'ppm' => 'image/x-portable-pixmap',
        'ppt' => 'application/vnd.ms-powerpoint',
        'ps' => 'application/postscript',
        'ptid1' => 'application/vnd.pvi.ptid1',
        'pti' => 'image/prs.pti',
        'publishare-delta-tree' => 'application/vnd.publishare-delta-tree',
        'pwg-xhtml-print+xml' => 'application/vnd.pwg-xhtml-print+xml',
        'qbo' => 'application/vnd.intu.qbo',
        'qcelp' => 'audio/vnd.qcelp',
        'qfx' => 'application/vnd.intu.qfx',
        'qsig' => 'application/qsig',
        'qt' => 'video/quicktime',
        'quickanime' => 'application/vnd.epson.quickanime',
        'quickcall' => 'application/vnd.ericsson.quickcall',
        'quicktime' => 'video/quicktime',
        'ra' => 'audio/x-realaudio',
        'ram' => 'audio/x-pn-realaudio',
        'rapid' => 'application/vnd.rapid',
        'ras' => 'image/x-cmu-raster',
        'reflex' => 'text/vnd.motorola.reflex',
        'related' => 'multipart/related',
        'remote-printing' => 'application/remote-printing',
        'report' => 'multipart/report',
        'response' => 'application/index.response',
        'rfc822-headers' => 'text/rfc822-headers',
        'rfc822' => 'message/rfc822',
        'rgb' => 'image/x-rgb',
        'richtext' => 'text/richtext',
        'riscos' => 'application/riscos',
        'rm' => 'audio/x-pn-realaudio',
        'roff' => 'application/x-troff',
        'rpm' => 'audio/x-pn-realaudio-plugin',
        'rtf' => 'application/rtf',
        'rtf' => 'text/rtf',
        'rtx' => 'text/richtext',
        's3sms' => 'application/vnd.s3sms',
        'salt' => 'application/vnd.epson.salt',
        'sbc' => 'audio/vnd.octel.sbc',
        'scriptfile' => 'application/vnd.vividence.scriptfile',
        'sdp' => 'application/sdp',
        'seemail' => 'application/vnd.seemail',
        'series' => 'application/vnd.ecowin.series',
        'seriesrequest' => 'application/vnd.ecowin.seriesrequest',
        'seriesupdate' => 'application/vnd.ecowin.seriesupdate',
        'set-payment' => 'application/set-payment',
        'set-payment-initiation' => 'application/set-payment-initiation',
        'set-registration' => 'application/set-registration',
        'set-registration-initiation' => 'application/set-registration-initiation',
        'sgml' => 'application/sgml',
        'sgml-open-catalog' => 'application/sgml-open-catalog',
        'sgml' => 'text/sgml',
        'sgm' => 'text/sgml',
        'sh' => 'application/x-sh',
        'shar' => 'application/x-shar',
        's-http' => 'message/s-http',
        'sic' => 'application/vnd.wap.sic',
        'sid' => 'audio/prs.sid',
        'sieve' => 'application/sieve',
        'signal' => 'application/vnd.uplanet.signal',
        'signed' => 'multipart/signed',
        'silo' => 'model/mesh',
        'sit' => 'application/x-stuffit',
        'si' => 'text/vnd.wap.si',
        'skd' => 'application/x-koan',
        'skm' => 'application/x-koan',
        'skp' => 'application/x-koan',
        'skt' => 'application/x-koan',
        'slate' => 'application/slate',
        'slc' => 'application/vnd.wap.slc',
        'sl' => 'text/vnd.wap.sl',
        'smi' => 'application/smil',
        'smil' => 'application/smil',
        'snd' => 'audio/basic',
        'so' => 'application/octet-stream',
        'spl' => 'application/x-futuresplash',
        'spot' => 'text/vnd.in3d.spot',
        'src' => 'application/x-wais-source',
        'ssf' => 'application/vnd.epson.ssf',
        'sss-cod' => 'application/vnd.sss-cod',
        'sss-dtf' => 'application/vnd.sss-dtf',
        'sss-ntf' => 'application/vnd.sss-ntf',
        'stf' => 'application/vnd.wt.stf',
        'street-stream' => 'application/vnd.street-stream',
        'sv4cpio' => 'application/x-sv4cpio',
        'sv4crc' => 'application/x-sv4crc',
        'svd' => 'application/vnd.svd',
        'svf' => 'image/vnd.svf',
        'swf' => 'application/x-shockwave-flash',
        'swiftview-ics' => 'application/vnd.swiftview-ics',
        't140' => 'text/t140',
        'tab-separated-values' => 'text/tab-separated-values',
        'tag' => 'text/prs.lines.tag',
        't' => 'application/x-troff',
        'tar' => 'application/x-tar',
        'tcl' => 'application/x-tcl',
        'telephone-event' => 'audio/telephone-event',
        'tex' => 'application/x-tex',
        'texi' => 'application/x-texinfo',
        'texinfo' => 'application/x-texinfo',
        'tiff' => 'image/tiff',
        'tif' => 'image/tiff',
        'timestamp-query' => 'application/timestamp-query',
        'timestamp-reply' => 'application/timestamp-reply',
        'titrax-sheet' => 'application/prs.alvestrand.titrax-sheet',
        'tone' => 'audio/tone',
        'tr' => 'application/x-troff',
        'trueapp' => 'application/vnd.trueapp',
        'truedoc' => 'application/vnd.truedoc',
        'trustweb' => 'application/vnd.mitsubishi.misty-guard.trustweb',
        'tsv' => 'text/tab-separated-values',
        'ttc' => 'application/vnd.motorola.flexsuite.ttc',
        'tve-trigger' => 'application/vnd.tve-trigger',
        'txf' => 'application/vnd.mobius.txf',
        'txt' => 'text/plain',
        'ufdl' => 'application/vnd.ufdl',
        'uri-list' => 'text/uri-list',
        'ustar' => 'application/x-ustar',
        'vbk' => 'audio/vnd.nortel.vbk',
        'vcd' => 'application/x-cdlink',
        'vcx' => 'application/vnd.vcx',
        'vectorworks' => 'application/vnd.vectorworks',
        'vemmi' => 'application/vemmi',
        'vidconference' => 'application/vnd.vidsoft.vidconference',
        'videop' => 'video/vnd.motorola.videop',
        'video' => 'video/vnd.motorola.video',
        'visio' => 'application/vnd.visio',
        'vivo' => 'video/vnd.vivo',
        'vnd' => 'application/index.vnd',
        'voice' => 'audio/vnd.lucent.voice',
        'voice-message' => 'multipart/voice-message',
        'vrml' => 'model/vrml',
        'vtu' => 'model/vnd.vtu',
        'wav' => 'audio/x-wav',
        'wbmp' => 'image/vnd.wap.wbmp',
        'wbxml' => 'application/vnd.wap.wbxml',
        'weblaunch' => 'application/vnd.fsc.weblaunch',
        'webturbo' => 'application/vnd.webturbo',
        'wem' => 'application/vnd.motorola.flexsuite.wem',
        'whoispp-query' => 'application/whoispp-query',
        'whoispp-response' => 'application/whoispp-response',
        'wita' => 'application/wita',
        'wmlc' => 'application/vnd.wap.wmlc',
        'wmlsc' => 'application/vnd.wap.wmlscriptc',
        'wmlscriptc' => 'application/vnd.wap.wmlscriptc',
        'wmlscript' => 'text/vnd.wap.wmlscript',
        'wmls' => 'text/vnd.wap.wmlscript',
        'wml' => 'text/vnd.wap.wml',
        'wmv' => 'video/x-ms-wmv',
        'wrl' => 'model/vrml',
        'wrq-hp3000-labelled' => 'application/vnd.wrq-hp3000-labelled',
        'x400-bp' => 'application/x400-bp',
        'x-aiff' => 'audio/x-aiff',
        'xara' => 'application/vnd.xara',
        'x-bcpio' => 'application/x-bcpio',
        'xbm' => 'image/x-xbitmap',
        'x-cdlink' => 'application/x-cdlink',
        'x-chess-pgn' => 'application/x-chess-pgn',
        'x-cmu-raster' => 'image/x-cmu-raster',
        'x-compress' => 'application/x-compress',
        'x-cooltalk' => 'x-conference/x-cooltalk',
        'x-cpio' => 'application/x-cpio',
        'x-csh' => 'application/x-csh',
        'x-director' => 'application/x-director',
        'x-dvi' => 'application/x-dvi',
        'xfdl' => 'application/vnd.xfdl',
        'x-futuresplash' => 'application/x-futuresplash',
        'x-gtar' => 'application/x-gtar',
        'x-gzip' => 'application/x-gzip',
        'x-hdf' => 'application/x-hdf',
        'xht' => 'application/xhtml+xml',
        'xhtml' => 'application/xhtml+xml',
        'xhtml+xml' => 'application/xhtml+xml',
        'xiff' => 'image/vnd.xiff',
        'x-javascript' => 'application/x-javascript',
        'x-koan' => 'application/x-koan',
        'x-latex' => 'application/x-latex',
        'xls' => 'application/vnd.ms-excel',
        'xml' => 'application/xml',
        'xml-dtd' => 'application/xml-dtd',
        'xml-external-parsed-entity' => 'application/xml-external-parsed-entity',
        'xml-external-parsed-entity' => 'text/xml-external-parsed-entity',
        'xml' => 'text/xml',
        'x-mpegurl' => 'audio/x-mpegurl',
        'x-msvideo' => 'video/x-msvideo',
        'x-netcdf' => 'application/x-netcdf',
        'x-pdb' => 'chemical/x-pdb',
        'xpm' => 'image/x-xpixmap',
        'x-pn-realaudio' => 'audio/x-pn-realaudio',
        'x-pn-realaudio-plugin' => 'audio/x-pn-realaudio-plugin',
        'x-portable-anymap' => 'image/x-portable-anymap',
        'x-portable-bitmap' => 'image/x-portable-bitmap',
        'x-portable-graymap' => 'image/x-portable-graymap',
        'x-portable-pixmap' => 'image/x-portable-pixmap',
        'x-realaudio' => 'audio/x-realaudio',
        'x-rgb' => 'image/x-rgb',
        'x-setext' => 'text/x-setext',
        'x-sgi-movie' => 'video/x-sgi-movie',
        'x-sh' => 'application/x-sh',
        'x-shar' => 'application/x-shar',
        'x-shockwave-flash' => 'application/x-shockwave-flash',
        'xsl' => 'text/xml',
        'x-stuffit' => 'application/x-stuffit',
        'x-sv4cpio' => 'application/x-sv4cpio',
        'x-sv4crc' => 'application/x-sv4crc',
        'x-tar' => 'application/x-tar',
        'x-tcl' => 'application/x-tcl',
        'x-tex' => 'application/x-tex',
        'x-texinfo' => 'application/x-texinfo',
        'x-troff' => 'application/x-troff',
        'x-troff-man' => 'application/x-troff-man',
        'x-troff-me' => 'application/x-troff-me',
        'x-troff-ms' => 'application/x-troff-ms',
        'xul+xml' => 'application/vnd.mozilla.xul+xml',
        'x-ustar' => 'application/x-ustar',
        'x-wais-source' => 'application/x-wais-source',
        'x-wav' => 'audio/x-wav',
        'xwd' => 'image/x-xwindowdump',
        'x-xbitmap' => 'image/x-xbitmap',
        'x-xpixmap' => 'image/x-xpixmap',
        'x-xwindowdump' => 'image/x-xwindowdump',
        'x-xyz' => 'chemical/x-xyz',
        'xyz' => 'chemical/x-xyz',
        'yellowriver-custom-menu' => 'application/vnd.yellowriver-custom-menu',
        'zip' => 'application/zip',
        ); //end mime_array

    if ( isset($mime_array[$tmp]) ) {
        $res = $mime_array[$tmp];
    } else {
        $res = '';
    }
    return $res;
} // end fn mime_content_type
//} //end function_exists check

/*
 * $Log: mime-array.php,v $
 * Revision 1.6  2006/02/03 21:46:20  jswalter
 *  - added 'wmv' to MIME type list
 *
 * Revision 1.5  2005/07/06 18:16:20  braverock
 * - change back to custom function name as php mime_content_type fn
 *   causes problems on several configs
 *
 * Revision 1.4  2005/07/06 14:21:39  braverock
 * - change name of function to mime_content_type
 * - add phpdoc
 * - only declare function if php core fn mime_content_type doesn't exist
 *
 * Revision 1.3  2004/08/03 18:04:57  cpsource
 * - Global our main array
 *
 * Revision 1.2  2004/08/03 16:52:06  cpsource
 * - Create function mime_get_type to return the mime type from
 *   the system file name.
 *
 * Revision 1.1  2004/08/02 14:11:15  cpsource
 * - Translate mime types per specifications
 *
 */
?>