<?php

//
// all paths are now relative to this file ONLY
//

$include_locations_location = '../';
require_once($include_locations_location . 'include-locations.inc');

/**
 * $Log: include-locations-location.inc,v $
 * Revision 1.2  2004/09/21 18:38:14  introspectshun
 * - Corrected errant commit
 *
 * Revision 1.1  2004/08/04 21:46:42  introspectshun
 * - Localized strings for i18n/l10n support
 * - All paths now relative to include-locations-location.inc
 *
 */

?>
