<?php
# How checkboxes values should be shown
$checkbox_set = _("yes");
$checkbox_clear = _("no");

# Titles
$server_info_heading = _("Information");
$server_list = _("List");
$server_heading = _("Item");
$company_heading = _("Company");
$edit_server_details = _("Edit Details");
$new_server_details = _("Add New Info");

# What we call different element types
$text = _("text");
$textarea = _("textbox");
$radio = _("radio buttons");
$checkbox = _("checkbox");
$select = _("combo");

# Sort by company or server name on the Server Info page
$sort_by_companyname = false;

?>
