<?php
/**
 *  Login:Auto Plugin
 *  By Brendon Baumgartner <brendon@brendon.com>
 *  Orinally programmed for Squirrelmail By Jay Guerette
 *  (c) 2005 (GNU GPL - see ../../COPYING)
 *
 *  If you need help with this, or see improvements that can be made, please
 *  email the XRMS Plugins mailing list or try contacting me at
 *  the address above. I definately welcome suggestions and comments.
 *  This plugin, is not directly supported by the developers.
 *
 *  View the INSTALL document for information on installing this.  Also view
 *  the README document and plugins/README.plugins for more information.
 *
 * $Id: security.php,v 1.3 2006/04/05 01:20:26 vanmer Exp $
 */


   define('SM_PATH','../../');
   include_once(SM_PATH . 'config/config.php');
   include_once(SM_PATH . 'plugins/login_auto/config.php');

?>
<HTML>
   <HEAD>
<?php
   if ($theme_css != '') {
?>
<LINK REL="stylesheet" TYPE="text/css" HREF="<?php echo $theme_css ?>">
<?php
   }
?>
<TITLE><?php echo _("Security Notice"); ?></TITLE>
</HEAD>
<BODY>
<BR><BR>
<TABLE BGCOLOR="FFFFFF" BORDER="0" COLS="1" WIDTH="90%" CELLSPACING="0"
CELLPADDING="2" ALIGN="CENTER">
  <TR>
    <TD>
    <b>
<?php echo _("What does 'Remember My Name & Password' mean?"); ?>
    </b>
    </TD>
  </TR>
  <TR>
    <TD>
<?php
echo _("When you sign in with your name and password, your browser can 'remember' or store this information. Check the box and you won't have to enter this information each time you come back. If you don't log in for a period of time set by your administrator, this information will be 'forgotten'.");
echo '<br>'. _("The time limit is currently set to:").' ';
global $auto_expire_days, $auto_expire_hours, $auto_expire_minutes;
$x=$auto_expire_days*86400 + $auto_expire_hours*3600 + $auto_expire_minutes*60;
if ($x<60) echo (int)$x.' '._("seconds");
elseif ($x<3600) echo (int)($x/60).' '._("minutes");
elseif ($x<86400) echo (int)($x/3600).' '._("hours");
else echo (int)($x/86400).' '._("days");
?>

    </TD>
  </TR>
  <TR>
    <TD>
    <br><b><?php echo _("Should I be concerned about security?");?></b>
    </TD>
  </TR>
  <TR>
    <TD>
<?php
    echo _("If you are concerned that other people might attempt to access your XRMS CRM account, do not check the 'Remember my Name & Password' box. You may want be sure to click 'Log Out' when you leave your computer, which ensures that you will be asked for your login information the next time anyone accesses XRMS CRM from your computer.")
    .'<br>'
    ._("If you use a shared computer (in a library, Internet cafe, university, airport or other common area) <b>DO NOT</b> check the 'Remember my Name & Password' checkbox.")
    .'<br>'
?>
    </TD>
  </TR>
<?php
if ($auto_user && !$auto_pass)
{ //only name stored
?>
  <TR>
    <TD>
    <br><b>
    <?php _("Is saving just my name really a security risk?"); ?>
    </b>
    </TD>
  </TR>
  <TR>
    <TD>
    <?php
        echo _("By providing one-half of the key needed to access your account, you are making it slightly easier for someone to attempt to gain access. In most situations this option is safe; however you should think about who else may have access to your computer, and be aware of the slightly increased risk.");
    ?>
    </TD>
  </TR>
<?php
} //end if store name only
?>
  <TR>
    <TD>
    <br><b><?php echo _("What if I change my mind?"); ?></b>
    </TD>
  </TR>  <TR>
    <TD>
<?php
    echo ($auto_user && !$auto_pass)?
    _("When you login, just uncheck the 'Remember my Name' checkbox."):'';

    echo _("You can always sign out at any time by clicking the 'Log Out' link at the top of each page. This will erase the stored login information. Once you've signed out, you can sign in again and choose whether or not your browser should 'remember' your login information.");
?>
    </TD>
  </TR>
  <TR>
    <TD>
    <br><b><?php echo _("How does this work?") ?></b>
    </TD>
  </TR>
  <TR>
    <TD>
    <?php
        echo _("We do this with something called persistent cookies. Cookies are pieces of information generated by a Web Server and stored in the user's computer by the browser. By enabling 'Remember my Name' or 'Remember my Name and Password' you are instructing the server to store your information in an encrypted fashion on your computer.  Each time you login to this mail server, your encrypted name (and your password if you request it) are retrieved from your browser by the server. Clicking the 'Log Out' link will erase these cookies.");
    ?>
    </TD>
  </TR>
</TABLE>
</BODY>
</HTML>

<?php
/**
 * $Log: security.php,v $
 * Revision 1.3  2006/04/05 01:20:26  vanmer
 * - fixed parse errors in plugin
 *
 * Revision 1.2  2005/11/27 15:17:30  braverock
 * - relocalize some strings... foiled by editor auto-save
 *
 */
?>