<?php
# How checkboxes values should be shown
$checkbox_set = "yes";
$checkbox_clear = "no";

# Titles
$server_info_heading = "Server information";
$server_list = "Server List";
$server_heading = "Server";
$company_heading = "Company";
$edit_server_details = "edit details";
$new_server_details = "add new server";

# What we are listing in the sidebar
$servers = "Servers";

# What we call different element types
$text = "text";
$textarea = "textbox";
$radio = "radio buttons";
$checkbox = "checkbox";
$select = "combo";

# Sort by company or server name on the Server Info page
$sort_by_companyname = false;

?>
