CREATE TABLE `cti_cisco_7960_config` (
`id` int(11) NOT NULL auto_increment,
`mac` VARCHAR( 100 ) NOT NULL ,
`ip` VARCHAR( 100 ) NULL ,
`proxy1_address` VARCHAR( 100 ) NULL ,
`line1_name` VARCHAR( 100 ) NULL ,
`line1_displayname` VARCHAR( 100 ) NULL ,
`line1_authname` VARCHAR( 100 ) NULL ,
`line1_password` VARCHAR( 100 ) NULL ,
`proxy2_address` VARCHAR( 100 ) NULL ,
`line2_name` VARCHAR( 100 ) NULL ,
`line2_displayname` VARCHAR( 100 ) NULL ,
`line2_authname` VARCHAR( 100 ) NULL ,
`line2_password` VARCHAR( 100 ) NULL ,
`proxy3_address` VARCHAR( 100 ) NULL ,
`line3_name` VARCHAR( 100 ) NULL ,
`line3_displayname` VARCHAR( 100 ) NULL ,
`line3_authname` VARCHAR( 100 ) NULL ,
`line3_password` VARCHAR( 100 ) NULL ,
`proxy4_address` VARCHAR( 100 ) NULL ,
`line4_name` VARCHAR( 100 ) NULL ,
`line4_displayname` VARCHAR( 100 ) NULL ,
`line4_authname` VARCHAR( 100 ) NULL ,
`line4_password` VARCHAR( 100 ) NULL ,
`proxy5_address` VARCHAR( 100 ) NULL ,
`line5_name` VARCHAR( 100 ) NULL ,
`line5_displayname` VARCHAR( 100 ) NULL ,
`line5_authname` VARCHAR( 100 ) NULL ,
`line5_password` VARCHAR( 100 ) NULL ,
`proxy6_address` VARCHAR( 100 ) NULL ,
`line6_name` VARCHAR( 100 ) NULL ,
`line6_displayname` VARCHAR( 100 ) NULL ,
`line6_authname` VARCHAR( 100 ) NULL ,
`line6_password` VARCHAR( 100 ) NULL ,
`proxy_emergency` VARCHAR( 100 ) NULL ,
`proxy_emergency_port` VARCHAR( 100 ) NULL ,
`proxy_backup` VARCHAR( 100 ) NULL ,
`proxy_backup_port` VARCHAR( 100 ) NULL ,
`outbound_proxy` VARCHAR( 100 ) NULL ,
`outbound_proxy_port` VARCHAR( 100 ) NULL ,
`nat_enable` VARCHAR( 100 ) NULL ,
`nat_address` VARCHAR( 100 ) NULL ,
`voip_control_port` VARCHAR( 100 ) NULL ,
`start_media_port` VARCHAR( 100 ) NULL ,
`end_media_port` VARCHAR( 100 ) NULL ,
`nat_received_processing` VARCHAR( 100 ) NULL ,
`phone_label` VARCHAR( 100 ) NULL ,
`time_zone` VARCHAR( 100 ) NULL ,
`telnet_level` VARCHAR( 100 ) NULL ,
`phone_prompt` VARCHAR( 100 ) NULL ,
`phone_password` VARCHAR( 100 ) NULL ,
`enable_vad` VARCHAR( 100 ) NULL ,
`network_media_type` VARCHAR( 100 ) NULL ,
`user_info` VARCHAR( 100 ) NULL ,
`logo_url` VARCHAR( 100 ) NULL ,
`messages_uri` VARCHAR( 100 ) NULL ,
`user_id` INT( 11 ) NULL ,
`entered_at` DATE NULL ,
`entered_by` INT( 11 ) NULL ,
`vm_email` VARCHAR( 100 ) NULL ,
`vm_password` VARCHAR( 100 ) NULL ,
`full_name` VARCHAR ( 100 ) NULL ,
`context` VARCHAR( 100 ) NULL ,
`extension` TINYINT( 6 ) NULL,
 KEY `id` (`id`)
);
