<?php

//
// all paths are now relative to this file ONLY
//

$include_locations_location = '../';
require_once($include_locations_location . 'include-locations.inc');

/**
 * $Log: include-locations-location.inc,v $
 * Revision 1.2  2004/07/22 11:21:13  cpsource
 * - All paths now relative to include-locations-location.inc
 *   Code cleanup for Create Contact for 'Self'
 *
 * Revision 1.1  2004/07/22 11:00:56  cpsource
 * - All paths are now relative to this ONE file.
 *
 */

?>
